apiVersion: v1
kind: Service
metadata:
  name: enayak-final-flask-service
  labels:
    username: enayak
    env: test
spec:
  type: ClusterIP
  selector:
    app: enayak-final-flask
  ports:
  - name: final-flask
    port: 5000
    targetPort: 5000
