apiVersion: apps/v1
kind: Deployment
metadata:
  name: eesha-test-flask-deployment
  labels:
    app: enayak-test-flask
    username: enayak
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enayak-test-flask
  template:
    metadata:
      labels:
        app: enayak-test-flask
        username: enayak
        env: test
    spec:
      containers:
        - name: helloflask
          imagePullPolicy: Always
          image: eeshanayak/flask-image
          env:
          - name: FLASK_APP
            value: "app.py"
          ports:
          - name: http
            containerPort: 5000
