apiVersion: v1
kind: Service
metadata:
  name: enayak-hw7-flask-service
  labels:
    username: enayak
    env: test
spec:
  type: ClusterIP
  selector:
    app: enayak-hw7-flask
  ports:
  - name: helloflask
    port: 5000
    targetPort: 5000
