apiVersion: v1
kind: Pod
metadata:
  name: homework05b
  labels:
    greeting: personalized
spec:
  containers:
    - name: hello
      image: ubuntu:18.04
      env:
      - name: NAME
        value: 'Eesha'
      command: ['sh', '-c', 'echo "Hello, $(NAME)" && sleep 3600']
